title: Rajdeep's Academic Notebook
description: A notebook to keep track of all my coursework.
theme: just-the-docs

url: https://just-the-docs.github.io

#aux_links:
   #Template Repository: https://github.com/just-the-docs/just-the-docs-template
