title: Coursework Notebook
description: A notebook to keep track of all my coursework.
theme: just-the-docs
url: https://raj-ch017.github.io/academic-notebook/

aux_links:
  "Way to website":
    - "https://raj-ch017.github.io/"
    
back_to_top: true
back_to_top_text: "Back to top"

